### ISSUE TITLE
Class type label hidden in mobile

### ISSUE THREAD

**Issue by QwertyMD** [BIC-DevSphere/routine-v2-react#16]
## Current Behavior:
When the dimension of the screen is reduced to mobile view, the class type label is hidden.
![brave_NwmqE0nVYe](https://github.com/user-attachments/assets/a5202bd8-65eb-46c3-a44a-bcecec7d7121)

## Expected Behavior:
The class type label should instead appear on top of the module title when on mobile dimension.

**Comment by Aadithapa456** [comment]
Assigned to you

**Comment by Aadithapa456** [comment]
Resolved.
